In [ ]:
import os
import numpy as np
import pandas as pd

folder_path = r"D:\OneDrive\Trading\Market Making\data\runs\run_20260702_013525"

events = pd.read_parquet(os.path.join(folder_path, "events.parquet"))

def generate_datasets(events):
    events = events.sort_values("ts").copy()
    events.to_parquet(os.path.join(folder_path, "events.parquet"), index=False)

generate_datasets(events)
print(len(events))
events

print(type(events[0]["ts"]))

79

     type             ts                                                msg
0   depth  1782956126314  {"e":"depthUpdate","E":1782956126314,"s":"BTCU...
1   depth  1782956126414  {"e":"depthUpdate","E":1782956126414,"s":"BTCU...
2   depth  1782956126514  {"e":"depthUpdate","E":1782956126514,"s":"BTCU...
3   depth  1782956126615  {"e":"depthUpdate","E":1782956126615,"s":"BTCU...
4   depth  1782956126714  {"e":"depthUpdate","E":1782956126714,"s":"BTCU...
..    ...            ...                                                ...
74  depth  1782956131314  {"e":"depthUpdate","E":1782956131314,"s":"BTCU...
75  depth  1782956131414  {"e":"depthUpdate","E":1782956131414,"s":"BTCU...
76  trade  1782956131467  {"e":"trade","E":1782956131467,"s":"BTCUSDT","...
77  trade  1782956131467  {"e":"trade","E":1782956131467,"s":"BTCUSDT","...
78  depth  1782956131514  {"e":"depthUpdate","E":1782956131514,"s":"BTCU...

[79 rows x 3 columns]

In [ ]:
import os
import glob
import numpy as np
import pandas as pd

folder_path = r"D:\OneDrive\Trading\Market Making\data\runs\run_20260702_130317"

def chunk_id(path):
    return int(os.path.basename(path).split("_")[1].split(".")[0])

trade_files = sorted(glob.glob(os.path.join(folder_path, "trades_*.parquet")), key = chunk_id)
trades_df = pd.concat((pd.read_parquet(f) for f in trade_files), ignore_index=True)

trades_df

,ts,symbol,price,price_tick,qty,side,is_buyer_maker,mid,microprice,microprice_dev,...,ask_size,trade_to_mid,trade_to_microprice,price_to_best_bid,price_to_best_ask,trade_side,trade_sign,notional,log_notional,intensity
0,1782997398407,BTCUSDT,61599.07,6159907,0.01987,BUY,False,0.000,0.000000,0.000000,...,0.00000,61599.070,61599.070000,61599.07,61599.07,BUY_AGGRESSOR,1,1223.973521,7.110675,1.987000e+07
1,1782997399216,BTCUSDT,61599.07,6159907,0.00104,BUY,False,61599.065,61599.062340,-0.002660,...,3.03555,0.005,0.007660,0.01,0.00,BUY_AGGRESSOR,1,64.063033,4.175357,2.618981e-04
2,1782997399441,BTCUSDT,61599.06,6159906,0.01433,SELL,True,61599.065,61599.062338,-0.002662,...,3.03639,-0.005,-0.002338,0.00,-0.01,SELL_AGGRESSOR,-1,882.714530,6.784134,3.608517e-03
3,1782997399871,BTCUSDT,61599.07,6159907,0.00734,BUY,False,61599.065,61599.062307,-0.002693,...,3.03726,0.005,0.007693,0.01,0.00,BUY_AGGRESSOR,1,452.137174,6.116195,1.855269e-03
4,1782997400347,BTCUSDT,61599.06,6159906,0.02333,SELL,True,61599.065,61599.062789,-0.002211,...,2.71636,-0.005,-0.002789,0.00,-0.01,SELL_AGGRESSOR,-1,1437.106070,7.271082,6.179183e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,1782997413769,BTCUSDT,61603.79,6160379,0.00017,SELL,True,61603.795,61603.792731,-0.002269,...,3.05389,-0.005,-0.002731,0.00,-0.01,SELL_AGGRESSOR,-1,10.472644,2.439965,4.038273e-05
376,1782997413769,BTCUSDT,61603.79,6160379,0.00009,SELL,True,61603.795,61603.792731,-0.002269,...,3.05389,-0.005,-0.002731,0.00,-0.01,SELL_AGGRESSOR,-1,5.544341,1.878601,2.137909e-05
377,1782997413769,BTCUSDT,61603.79,6160379,0.00009,SELL,True,61603.795,61603.792731,-0.002269,...,3.05389,-0.005,-0.002731,0.00,-0.01,SELL_AGGRESSOR,-1,5.544341,1.878601,2.137909e-05
378,1782997413769,BTCUSDT,61603.79,6160379,0.00009,SELL,True,61603.795,61603.792731,-0.002269,...,3.05389,-0.005,-0.002731,0.00,-0.01,SELL_AGGRESSOR,-1,5.544341,1.878601,2.137909e-05
379,1782997413769,BTCUSDT,61603.79,6160379,0.01173,SELL,True,61603.795,61603.792731,-0.002269,...,3.05389,-0.005,-0.002731,0.00,-0.01,SELL_AGGRESSOR,-1,722.612457,6.584256,2.786409e-03